name: CI/CD Pipeline
on:
  push:
    branches:
      - main # Ganti dengan nama branch yang ingin kamu gunakan
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2' # Ganti dengan versi PHP yang kamu gunakan
        extensions: mbstring, xml, mysql
    - name: Install Composer dependencies
      run: composer install --no-dev --optimize-autoloader
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Deploy to shared hosting via FTP
      env:
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
      run: |
        lftp -u $FTP_USERNAME,$FTP_PASSWORD -e "mirror -R ./ $DEPLOY_PATH; bye" $SERVER_IP
